# Generated by Django 4.2 on 2024-06-07 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_brand_description_alter_invoice_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditcard',
            options={},
        ),
    ]
