# Generated by Django 4.2 on 2024-06-07 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_creditcard_paymentmethod_delete_paymenttransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcard',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
